library(data.table)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(viridis)
library(gridExtra)
args<-commandArgs(TRUE)
dirin=args[1]
dirout=args[2]
lpop=args[3]
lpop<-unlist(strsplit(lpop,','))
#lpop<-c('us','all','Ligustica_Carnica','Mellifera','hybrid')

pdf(dirout,'/gmat.pdf',width=15,height=10)
for(i in 1:length(lpop)){
	popi<-lpop[i]
	fam<-fread(paste0(dirin,'/geno_hom_',popi,'_maf.fam'),data.table=F)
	gmat_ldak_bed<-fread(paste0(dirout,'/LDAKgmat_',popi,'_bed.grm.raw'),data.table=F)
	gmat_ldak_bed<-cbind(fam[,2],gmat_ldak_bed)
	colnames(gmat_ldak_bed)<-c('id',fam[,2])
	gmat_ldak_bimbam<-fread(paste0(dirout,'/LDAKgmat_',popi,'_bimbam.grm.raw'),data.table=F)
	gmat_ldak_bimbam<-cbind(fam[,2],gmat_ldak_bimbam)
	colnames(gmat_ldak_bimbam)<-c('id',fam[,2])
	gmat_ldak_freq<-fread(paste0(dirout,'/LDAKgmat_',popi,'_freq.grm.raw'),data.table=F)
	gmat_ldak_freq<-cbind(fam[,2],gmat_ldak_freq)
	colnames(gmat_ldak_freq)<-c('id',fam[,2])
	gmat_gemma_bed<-fread(paste0(dirout,'/g_matrix_',popi,'_bed.cXX.txt'),data.table=F)
	gmat_gemma_bed<-cbind(fam[,2],gmat_gemma_bed)
	colnames(gmat_gemma_bed)<-c('id',fam[,2])
	gmat_gemma_bimbam<-fread(paste0(dirout,'/g_matrix_',popi,'_bimbam.cXX.txt'),data.table=F)
	gmat_gemma_bimbam<-cbind(fam[,2],gmat_gemma_bimbam)
	colnames(gmat_gemma_bimbam)<-c('id',fam[,2])
	gmat_gemma_freq<-fread(paste0(dirout,'/g_matrix_',popi,'_freq.cXX.txt'),data.table=F)
	gmat_gemma_freq<-cbind(fam[,2],gmat_gemma_freq)
	colnames(gmat_gemma_freq)<-c('id',fam[,2])
	x_ldak_bed<-melt(gmat_ldak_bed)
	x_ldak_bed$id<-factor(x_ldak_bed$id,levels=unique(x_ldak_bed$id))
	x_ldak_bed$variable<-factor(x_ldak_bed$variable,levels=unique(x_ldak_bed$id))
	x_ldak_bimbam<-melt(gmat_ldak_bimbam)
	x_ldak_bimbam$id<-factor(x_ldak_bimbam$id,levels=unique(x_ldak_bimbam$id))
	x_ldak_bimbam$variable<-factor(x_ldak_bimbam$variable,levels=unique(x_ldak_bimbam$id))
	x_ldak_freq<-melt(gmat_ldak_freq)
	x_ldak_freq$id<-factor(x_ldak_freq$id,levels=unique(x_ldak_freq$id))
	x_ldak_freq$variable<-factor(x_ldak_freq$variable,levels=unique(x_ldak_freq$id))
	x_gemma_bed<-melt(gmat_gemma_bed)
	x_gemma_bed$id<-factor(x_gemma_bed$id,levels=unique(x_gemma_bed$id))
	x_gemma_bed$variable<-factor(x_gemma_bed$variable,levels=unique(x_gemma_bed$id))
	x_gemma_bimbam<-melt(gmat_gemma_bimbam)
	x_gemma_bimbam$id<-factor(x_gemma_bimbam$id,levels=unique(x_gemma_bimbam$id))
	x_gemma_bimbam$variable<-factor(x_gemma_bimbam$variable,levels=unique(x_gemma_bimbam$id))
	x_gemma_freq<-melt(gmat_gemma_freq)
	x_gemma_freq$id<-factor(x_gemma_freq$id,levels=unique(x_gemma_freq$id))
	x_gemma_freq$variable<-factor(x_gemma_freq$variable,levels=unique(x_gemma_freq$id))
	p1<-ggplot(x_ldak_bed,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('ldak_bed')
	p2<-ggplot(x_ldak_bimbam,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('ldak_bimbam')
	p3<-ggplot(x_ldak_freq,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('ldak_freq')
	p4<-ggplot(x_gemma_bed,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('gemma_bed')
	p5<-ggplot(x_gemma_bimbam,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('gemma_bimbam')
	p6<-ggplot(x_gemma_freq,aes(x=id,y=variable))+
		geom_tile(aes(fill=value))+
		scale_fill_gradient(low="blue",high="yellow")+
		theme(legend.position='none',axis.ticks=element_blank(),axis.text=element_blank())+
		ggtitle('gemma_freq')
	grid.arrange(p1,p2,p3,p4,p5,p6,nrow=2,top=popi)
	}
dev.off()

